Added polling ability

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,14 +1,32 @@
 #!/usr/bin/env bash
 
-root="http://10.0.0.1:5000/rootDesc.xml"
+root=${PORTICAL_UPNP_ROOT_URL}
+duration=${PORTICAL_POLL_INTERVAL-15}
 label="portical.upnp.forward"
-verbose=0  # 0 for silent, 1 for verbose
+verbose=false
+
+while (( "$#" )); do
+  case $1 in
+    -r | --root) root="$2"; shift 2 ;;
+    -d | --duration) duration="$2"; shift 2 ;;
+    -l | --label) label="$2"; shift 2 ;;
+    -v | --verbose) verbose=true; shift ;;
+    *) break ;;
+  esac
+done
+
 
 function run_cmd() {
-    if [[ $verbose -eq 1 ]]; then
-        "$@"  # Execute the command normally
+    if $verbose; then
+        "$@"
     else
-        "$@" > /dev/null 2>&1  # Discard both stdout and stderr
+        "$@" > /dev/null 2>&1
+    fi
+
+    local status=$?
+    if [ $status -ne 0 ]; then
+        echo "Error: Command '$*' failed with status $status"
+        exit $status
     fi
 }
 
@@ -39,16 +57,15 @@ function forward() {
 
   echo -n "Removing existing rule (if exists)... "
   run_cmd docker run --rm --network ${network} danielbodart/portical \
-    upnpc -u "${root}" -d "${external_port}" "${protocol}"
+    upnpc ${root:+-u "$root"} -d "${external_port}" "${protocol}"
   echo "DONE"
 
   echo -n "Adding new rule... "
   run_cmd docker run --rm --network ${network} danielbodart/portical \
-    upnpc -u "${root}" -e "${description}" -r "${internal_port}" "${external_port}" "${protocol}"
+    upnpc ${root:+-u "$root"} -e "${description}" -r "${internal_port}" "${external_port}" "${protocol}"
   echo "DONE"
 
 }
-
 
 function extract_rule() {
   local regex="${label//./\\.}:([0-9]+):([0-9]+)(/(tcp|udp))?"
@@ -60,7 +77,7 @@ function extract_rule() {
   fi
 }
 
-function find() {
+function update() {
   echo "Finding all containers with label '${label}' set..."
   docker ps --filter "label=${label}" --format '{{.Names}}' | while read container; do
     labels=$(docker inspect -f '{{.Config.Labels}}' "$container")
@@ -81,7 +98,22 @@ function find() {
   upnpc -u "${root}" -l | grep portical
 }
 
+function poll() {
+  while true; do
+    update
+    echo "Sleeping for ${duration} seconds..."
+    sleep ${duration}
+  done
+}
 
-command="${1-find}"
-set +e; shift;
-$command "$@"
+
+command="${1-update}"
+shift
+
+if declare -f "$command" > /dev/null; then
+  set +e
+  "$command" "$@"
+else
+  echo "Error: '$command' is not a valid command." >&2
+  exit 1
+fi
